# Generated by Django 3.2.2 on 2021-06-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dp', models.ImageField(upload_to='pics')),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('role', models.CharField(choices=[('Owner', 'Owner'), ('Dealer', 'Dealer'), ('Worker', 'Worker')], default='Trainee', max_length=50)),
            ],
        ),
    ]
