# Generated by Django 3.2.2 on 2021-06-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_auto_20210627_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('bed', 'bed'), ('sofa', 'sofa'), ('cabinets', 'cabinets'), ('tables', 'tables'), ('chairs', 'chairs'), ('other', 'other')], default='other', max_length=50),
        ),
    ]
