# Generated by Django 3.2.2 on 2021-06-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_alter_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='pdesc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='pname',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pic',
            new_name='ppic',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='ptype',
        ),
    ]
