# Generated by Django 3.2.2 on 2021-06-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0005_auto_20210627_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='pics')),
                ('tag', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
    ]
