# Generated by Django 3.2.2 on 2021-06-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0006_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='active',
            field=models.CharField(choices=[('yes', 1), ('no', 2)], default='no', max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
