# Generated by Django 3.2.2 on 2021-06-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0007_auto_20210627_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='active',
            field=models.CharField(choices=[(1, 'yes'), (0, 'no')], default=0, max_length=50),
        ),
    ]
