# Generated by Django 3.2.2 on 2021-06-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0008_alter_home_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='active',
            field=models.IntegerField(choices=[(1, 1), (0, 0)], default=0, max_length=50),
        ),
    ]
