# Generated by Django 3.2.2 on 2021-07-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0011_alter_product_ptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdesc',
            field=models.CharField(max_length=1000),
        ),
    ]
