# Generated by Django 3.2.2 on 2021-07-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0013_auto_20210706_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='potype',
            field=models.CharField(choices=[('Biochromate based emusion', 'Biochromate based emusion'), ('diazo based', 'diazo based'), ('pure photo', 'pure photo'), ('-', '-')], default='-', max_length=50),
        ),
    ]
