# Generated by Django 3.2.2 on 2021-07-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0014_alter_product_potype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='potype',
            field=models.CharField(choices=[('Biochromate_based_emusion', 'Biochromate_based_emusion'), ('diazo_based', 'diazo_based'), ('Pure_photopolymer', 'Pure_photopolymer'), ('-', '-')], default='-', max_length=50),
        ),
    ]
