# Generated by Django 3.2.2 on 2021-07-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0015_alter_product_potype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('ppic', models.ImageField(upload_to='pics')),
                ('pdesc', models.CharField(max_length=1000)),
                ('potype', models.CharField(choices=[('Biochromate_based_emusion', 'Biochromate_based_emusion'), ('diazo_based', 'diazo_based'), ('Pure_photopolymer', 'Pure_photopolymer'), ('-', '-')], default='-', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='potype',
        ),
    ]
