# Generated by Django 3.2.2 on 2021-07-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0016_auto_20210706_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='active',
            field=models.IntegerField(choices=[(1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='year',
            field=models.IntegerField(),
        ),
    ]
